<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenFan.Linux.Hw</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenFan.Core\OpenFan.Core.csproj" />
  </ItemGroup>

</Project>
